# SCSS linter rules
#
# See https://github.com/brigade/scss-lint/blob/master/config/default.yml for defaults
linters:

  IdSelector:
    enabled: false

  NestingDepth:
    enabled: true
    max_depth: 5
    ignore_parent_selectors: false
